name: Lint

on:
  workflow_dispatch: # enable run button on github.com
  pull_request:

env:
  WORK_PATH: "./"
  LOCK_PATH: "./package-lock.json"

jobs:
  lint:
    name: Lint JS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "npm"
          cache-dependency-path: ${{ env.LOCK_PATH }}
      - name: Install dependencies
        run: npm install
        working-directory: ${{ env.WORK_PATH }}
      - name: Lint JS
        run: npm run build
        working-directory: ${{ env.WORK_PATH }}
        env:
          CI: true
